### ISSUE TITLE
何时能支持svga2.0呢

### ISSUE THREAD

**Issue by haliluya4** [svga/SVGAPlayer-Web-Lite#88]
目前播放2.0版的svga动画，会直接报错。

**Comment by wcldyx** [comment]
> 目前播放2.0版的svga动画，会直接报错。用SVGAPlayer-Web就可以播。
> 
> Uncaught TypeError: Cannot read properties of undefined (reading 'replace') at drawBezier (index.min.js:2:1) at drawShape (index.min.js:2:1) at eval (index.min.js:2:1) at Array.forEach () at drawSprite (index.min.js:2:1) at eval (index.min.js:2:1) at Array.forEach () at render (index.min.js:2:1) at e.drawFrame (index.min.js:2:1) at animator.onUpdate (index.min.js:2:1)

大佬有找到解决方案吗？，我这边也遇到同样的问题

**Comment by Naeemo** [comment]
可以提供一下 svga 文件。2.0应该是支持的，可能是个问题。

**Comment by haliluya4** [comment]
> 可以提供一下 svga 文件。2.0应该是支持的，可能是个问题。

可以试下这个，把后缀名改成svga就行。因为github不支持上传svga的，所以后缀名改成gif上传了。

![收藏 svga](https://github.com/svga/SVGAPlayer-Web-Lite/assets/4596557/0d470db2-71ca-45f0-b49b-410755d7d1e1)

**Comment by lijialiang** [comment]
能否提供一个最小能重现的 Github Repo 地址带上有问题的 SVGA 文件？

**Comment by Moillz** [comment]
> 能否提供一个最小能重现的 Github Repo 地址带上有问题的 SVGA 文件？

你好，我在使用svga的时候，遇到了同样的问题，经排查定位到问题出在是render.ts里的drawBezier函数，该函数的第二个入参d，replace操作没有处理d为undefined的异常，才导致运行时报错。以下是修改后的代码：

```js
function drawSprite (
  context: CanvasRenderingContext2D | OffscreenCanvasRenderingContext2D,
  sprite: VideoSprite,
  currentFrame: number,
  bitmap: Bitmap | undefined,
  replaceElement: ReplaceElement | undefined,
  dynamicElement: DynamicElement | undefined
): void {
  const frame = sprite.frames[currentFrame]

  if (frame.alpha < 0.05) return

  context.save()
  context.globalAlpha = frame.alpha

  context.transform(
    frame.transform?.a ?? 1,
    frame.transform?.b ?? 0,
    frame.transform?.c ?? 0,
    frame.transform?.d ?? 1,
    frame.transform?.tx ?? 0,
    frame.transform?.ty ?? 0
  )

  if (bitmap !== undefined) {
    if (frame.maskPath !== null) {
      drawBezier(context, frame.maskPath.d, frame.maskPath.transform, frame.maskPath.styles)
      context.clip()
    }
    if (replaceElement !== undefined) {
      context.drawImage(replaceElement, 0, 0, frame.layout.width, frame.layout.height)
    } else {
      context.drawImage(bitmap, 0, 0, frame.layout.width, frame.layout.height)
    }
  }

  if (dynamicElement !== undefined) {
    context.drawImage(dynamicElement, (frame.layout.width - dynamicElement.width) / 2, (frame.layout.height - dynamicElement.height) / 2)
  }

  // shape的path属性可能为空，所以需要判断
  frame.shapes.forEach(shape => drawShape(context, shape))

  context.restore()
}

function drawBezier (
  context: CanvasRenderingContext2D | OffscreenCanvasRenderingContext2D,
  d: string | undefined,
  transform: Transform | undefined,
  styles: VideoStyles
): void {
  context.save()
  resetShapeStyles(context, styles)
  if (transform !== undefined) {
    context.transform(
      transform.a,
      transform.b,
      transform.c,
      transform.d,
      transform.tx,
      transform.ty
    )
  }
  const currentPoint: CurrentPoint = { x: 0, y: 0, x1: 0, y1: 0, x2: 0, y2: 0 }
  context.beginPath()
  if (d !== undefined) {
    d = d.replace(/([a-zA-Z])/g, '|||$1 ').replace(/,/g, ' ')
    d.split('|||').forEach(segment => {
      if (segment.length === 0) return
      const firstLetter = segment.substr(0, 1)
      if (validMethods.includes(firstLetter)) {
        const args = segment.substr(1).trim().split(' ')
        drawBezierElement(context, currentPoint, firstLetter, args)
      }
    })
  }

  if (styles.fill !== null) {
    context.fill()
  }
  if (styles.stroke !== null) {
    context.stroke()
  }
  context.restore()
}
```
